### ISSUE TITLE
Shell's import gets included in all the bundles

### ISSUE THREAD

**Issue by a1626** [Polymer/polymer-bundler#489] opened 2017-04-27 16:34 UTC
Suppose we have an application having **4 entrypoints** (named Entrypoint 1, 2, 3, 4).
There dependencies are as flow

### Dependency tree

Entrypoint | Dependencies
------------ | -------------
Entrypoint 1 | Dep1.html, common.html 
Entrypoint 2 | Dep2.html, common.html
Entrypoint 3 | common.html
Entrypoint 4 | Dep1.html

Now, with **merge strategy set to 3** content of each file will be

### Output content

Entrypoint | element code | imports
------------ | ------------- | ---------------
Entrypoint 1 | entrypoint 1 | shell, shared_bundle_1
Entrypoint 2 | entrypoint 2, dep 2 | shell
Entrypoint 3 | entrypoint 3 | shell
Entrypoint 4 | entrypoint 4 | shared_bundle_1
shell | common | -
shared_bundle_1 | dep 1 | shell

Now, if user opens **Entrypoint 4** files from _shell_ will also be loaded even though they are not required by _Entrypoint 4_.

Ideally, none of the _shared_bundle_ should have import to shell as required _Entrypoint_ will always have it.

**Comment by web-padawan** [comment] 2017-04-27 16:49
Isn't it a duplicate of #471?

**Comment by a1626** [comment] 2017-04-27 18:00
Opening lines of the issue felt like they were same issue but i got a little confused with the problem statement as i read further. So i thought, i should raise the issue just to be on the safe side.

**Comment by usergenic** [comment] 2017-06-28 21:04
I would not expect that using the shell merge strategy would result in an additional shared_bundle_1...

**Comment by usergenic** [comment] 2017-06-28 21:05
@a1626 can you explain whether you were using Bundler programattically with `generateShellMergeStrategy()` or whether this was happening via `bin/polymer-bundler` or via `polymer --bundle`?

**Comment by a1626** [comment] 2017-06-29 06:07
@usergenic I think this one was from `cli`.

**Comment by usergenic** [comment] 2017-06-29 06:09
The results appear as if there was not shell specified though.  Did you have a polymer.json and did it have a 'shell' value?

**Comment by usergenic** [comment] 2017-06-29 06:11
Oh if you mean `cli` as in `bin/polymer-bundler` and not `polymer build` then polymer.json wouldn't matter.  You'd need to provide a `--shell <path-to-shell>` in the invocation.

**Comment by a1626** [comment] 2017-06-29 08:21
Yes, i did provide that.

**Comment by usergenic** [comment] 2017-06-29 18:49
@a1626 have a look at https://github.com/usergenic/examples/tree/polymer-bundler-issue-489 and tell me what i'm missing from your description.

there's no generated shared bundle my reproduction.

**Comment by a1626** [comment] 2017-06-29 19:48
You are right. Now, if look back at my question it says `with merge strategy set to 3` which cannot be achieved via cli.

Which means my last comment was wrong and i had used it programmatically, but i'm not able to find js file in my local project for the same issue. So, i'm a little confused.

**Comment by a1626** [comment] 2017-06-29 20:14
i finally remembered what i was doing. I used bundle from cli, but i changed `polymer-bundler.js` in __bin__ folder hard coding merge strategy to 3 instead of it's default value 2.

**Comment by usergenic** [comment] 2017-06-29 22:54
> Ideally, none of the shared_bundle should have import to shell as required Entrypoint will always have it.

The recent (yesterday) polymer-bundler 2.2.0 release did specifically address the issue where bundles linked back to shell.  Perhaps if you update and make the same change you'll get a better result?

**Comment by a1626** [comment] 2017-06-30 05:02
Yes, with `2.2.0` this problem is not there are import for shell has been removed from all the files.

This approach works fine for general scenario but what if lets say user uses some empty file as a shell for bundler, probably because his first few pages do not need any of the element in shell (common imports file). This way he'll have to manually go and enter import for common file in all the required entrypoints.

**Comment by web-padawan** [comment] 2017-06-30 06:15
In general, shell is assumed to be loaded at the app startup and to contain required dependencies. If you'd like to change this behavior, consider using `generateSharedDepsMergeStrategy` for a common file and then bundle your small shell separately, but you'll need to ensure no dependencies are being duplicated.

**Comment by a1626** [comment] 2017-06-30 06:29
@web-padawan If i use `generateSharedDepsMergeStrategy` (lets say with value set to 3), then all my dependencies repeat 3 or more time should go to shell and rest should go to separate bundle files.

Now assume, that user doesn't provide his actual shell as shell to bundler (probably because he doesn't need all the common files for first page). In that case that pseudo shell file will not be imported anywhere as bundler does not add that import anymore.

**Comment by usergenic** [comment] 2017-07-05 18:50
@a1626 I can't quite grok the subsequent problem you have described.  `generateSharedDepsMergeStrategy` is different than `generateShellMergeStrategy` in two ways:

 - `generateSharedDepsMergeStrategy` doesn't define a target/name for the merged bundle; `generateShellMergeStrategy` does.
 - `generateSharedDepsMergeStrategy` doesn't strip links to the merged bundle from dependent bundles; `generateShellMergeStrategy` does.

So in your example, if by "pseudo shell" you mean the shared bundle containing all imports depended on by at least 3 entrypoints, it would actually be imported by the fragments which need it.

In any event, I'm going to close this issue because it appears the original behavior discusses has been addressed by the shell backlinks being removed in new v2.2.0 -- If you encounter another problem, lets open a new issue.

Thanks!

**Closed by usergenic** 2017-07-05 18:50 UTC
Labels: Priority: Medium, Type: Question
