### ISSUE TITLE
Unable to get document when using FSUrlLoader (polymer-analyzer)

### ISSUE THREAD

**Issue by VandeurenGlenn** [Polymer/polymer-bundler#561] opened 2017-06-17 16:54 UTC
## code

```js
const analyzer = new Analyzer({
    urlLoader: new FSUrlLoader(join(process.cwd(), 'build/unbundled'))
});

const bundler = new polymerBundler.Bundler(config);

bundler.generateManifest('index.html').then(function (manifest) {
  console.log(manifest); // empty BundleManifest
  bundler.bundle(manifest).then(function (result) {
     console.log(result.documents.get('index.html').ast)
  });
  });
});
```

## result
![image](https://user-images.githubusercontent.com/8685280/27254658-0d4005c0-538d-11e7-8fd8-d65c2c6a9d7a.png)

**Comment by usergenic** [comment] 2017-06-20 17:59
`bundler.generateManifest(entrypoints: UrlString[])` <-- needs an array

Try:
`bundler.generateManifest(['index.html'])` ...

**Comment by usergenic** [comment] 2017-06-20 18:00
I'll file an issue to run some input checks on public API surface.  We rely a lot on TypeScript internally but want to guard against type errors in JS too.

**Comment by VandeurenGlenn** [comment] 2017-06-20 19:16
Actually I didn't quite explain good enough, the input is an array already and everything works, but when adding the analyzer It doesn't anymore and gives back above result

@usergenic

**Comment by usergenic** [comment] 2017-06-20 19:34
hmm.  can you output/confirm the result of `join(process.cwd(), 'build/unbundled')`

Also, I don't see the analyzer in the config (I assume that happened elsewhere?)

Suggest perhaps:
```javascript
const analyzer = new Analyzer({
    urlLoader: new FSUrlLoader(path.resolve('build/unbundled'))
});

const bundler = new polymerBundler.Bundler({
    analyzer: analyzer
});

bundler.generateManifest(['index.html']).then(function (manifest) {
  console.log(manifest); // empty BundleManifest
  bundler.bundle(manifest).then(function (result) {
     console.log(result.documents.get('index.html').ast)
  });
});
```

**Comment by VandeurenGlenn** [comment] 2017-06-21 10:11
The path is always as expected (D:\workspace\webup\build\unbundled).
I also tested multiple solutions:  join, resolve or just 'build/unbundled' all results are the same.
When setting a wrong path, an error is given that the file isn't found (as expected).

In the project its used in 2 different places
- [bundler](https://github.com/VandeurenGlenn/webup/blob/master/src/utils/bundler.js#L16)

- [preset](https://github.com/VandeurenGlenn/webup-preset-default/blob/55132ec754d610bf8067b61404f9b2c81af5b58a/src/default.js)

**Comment by usergenic** [comment] 2017-06-26 20:02
Can you check your node_modules folder-- there is a chance you have 2 different versions of polymer-analyzer.  If you do, you need to clean node_modules folder and install and make sure you have only one.  Bundler will report that the file is not gettable when the Document object is not an instance of the Document class defined by the version of polymer-analyzer that polymer-bundler is loading.

**Comment by usergenic** [comment] 2017-06-26 21:10
`npm ls polymer-analyzer`

**Comment by usergenic** [comment] 2017-06-26 21:14
fwiw we are looking at a solution for this problem because it comes up from time to time and the symptom is very misleading as to the root cause: https://github.com/Polymer/polymer-analyzer/pull/686

**Comment by usergenic** [comment] 2017-06-26 21:15
I'm going to close this issue because I am 90% sure that this is the cause of your problem.  If it turns out not to be so, please respond and we can reopen and investigate more thoroughly.  Thanks!

**Closed by usergenic** 2017-06-26 21:15 UTC
Labels: Priority: Medium, Type: Question

**Comment by VandeurenGlenn** [comment] 2017-06-27 17:26
I just checked and there is only one polymer-analyzer and under polymer-bundler,I already found a solution for my problem, was just reporting my findings, yw!

**Comment by cherukumilli** [comment] 2018-10-30 14:37
@VandeurenGlenn - I am running into the same problem. Can you please post how you resolved this problem?

**Comment by VandeurenGlenn** [comment] 2018-10-30 15:12
@cherukumilli I'll try doing this weekend, have to look into the code first.
