### ISSUE TITLE
Excludes option should honor js and css assets in addition to html imports

### ISSUE THREAD

**Issue by usergenic** [Polymer/polymer-bundler#548] opened 2017-06-13 19:55 UTC
The `excludes` option appears to only apply to html imports and folders containing those imports.  It needs to honor js and css assets as well.

**Comment by usergenic** [comment] 2017-06-13 19:56
@freshp86

**Comment by micschro** [comment] 2017-06-14 15:10
Isn't this a duplicate of #530?

**Comment by usergenic** [comment] 2017-06-14 20:11
Yep, duplicate of https://github.com/Polymer/polymer-bundler/issues/530

**Closed** 2017-06-14 20:11 UTC
Labels: Priority: High, Source: Hooli, Type: Enhancement
